language: php

php:
   - 7.1
   - 7.2

env:
   - SYMFONY_VERSION=2.8.*
   - SYMFONY_VERSION=3.4.*

matrix:
   fast_finish: true
   allow_failures:
      - php: hhvm

before_script:
   - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis.php.ini; fi;'
   - composer self-update
   - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --dev
   - composer update --prefer-dist --no-interaction

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover

after_script:
   - wget https://scrutinizer-ci.com/ocular.phar
   - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
   email:
      - php@h4cc.de
